### ISSUE TITLE
Question: what are the blandfruit relics?

### ISSUE THREAD

**Issue by AvangionQ** [BDWSSBB/StS-Strawberry-Spire#6]
Question about the Blandfruit Bush event: what are the blandfruit relics? What do they do?

Yes, am requesting spoilers, if you can call it that ...

**Comment by AvangionQ** [comment]
Guess I'll have to settle for some trial and error until a wiki editor can use this info ...
Sunfruit: whenever you climb a floor, heal 3 HP
Earthfruit: start each combat with 4 barkskin
(Barkskin damage reduction, losing 1 per turn)
Fadefruit: draw 1 extra card into your first turn hand

**Comment by BDWSSBB** [comment]
Blindfruit: Start each combat with 1 Intangible.
Dreamfruit: ALL debuffs you have last up to 1 turn.
Earthfruit: Start each combat with 4 Barkskin.
Fadefruit: At the start of each combat, put 1 card from your draw pile into your hand.
Firefruit: At the start of each combat, deal 15 damage to ALL enemies.
Icefruit: At the start of your first 3 turns, ALL enemies lose 1 Strength.
Rotfruit: At the start of your turn, gain 1 Strength.
Sorrowfruit: Whenever you apply a non-Poison debuff, apply 2 Poison.
Starfruit: Upon pickup, raise your Max HP by 8. This and future Max HP gains are 50% more effective.
Stormfruit: Whenever you Channel a Lightning, draw 1 card.
Sunfruit: Whenever you climb a floor, heal 3 HP.
Swiftfruit: Start each combat with 2 Dexterity.

**Comment by AvangionQ** [comment]
BDWSSBB, yuge thanks for that list, it's much appreciated ... 💖
